[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]
remappings = [

    # Uniswap v3-periphery expects this one:
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",

    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@chainlink/local/=lib/chainlink-local/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/swap-router-contracts/=lib/swap-router-contracts/",
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@uniswap/universal-router/=lib/universal-router/",
    "@uniswap/permit2/=lib/permit2/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC}"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
